### ISSUE TITLE
fesvr-zynq hangs

### ISSUE THREAD

**Issue by rajatsrao** [li3tuo4/rc-fpga-zcu#10]
I have followed the instructions to build all the files from scratch (could not use pre-built images due to different board version).
However, when I run `./fesvr-zynq pk hello` it just hangs and does not print anything. Same issue with bbl. I need to press Ctrl+C twice to get back. I believe pk and hello are built correctly because `spike pk hello` on the host works fine. For fesvr-zynq, I have tried both the prebuilt image and my freshly built one with the same result. How do I debug this? I wonder if there's an issue with HTIF or the rocket core itself.

Another question (maybe unrelated): Is a htif uio entry needed in the ARM's device tree? It doesn't look like fesvr-zynq is using /dev/uioX, but rather just /dev/mem.

**Comment by rajatsrao** [comment]
I put an ILA on the AXI-GP interface to see commands are being transferred. I see the write into the reset register at 0xa0000010. And then I see continuous reads for the FIFO counts at offsets 0x04 and 0x0C (from the poll function).
BUT, there's no write at all into the FIFO data register at offset 0x08. It looks like a tsi code problem. Any ideas what might be wrong?

**Comment by li3tuo4** [comment]
HTIF is realized and used in different layers of hardware and software, including device tree of ARM side system.  Which FPGA board are you using? Is your petalinux flow created by yourself or from this repo?  What did you change in your current build against this repo? You can wire the AXI signals coming from PL side for HTIF to an UART or something to see if rocket core is sending any HTIF request.

**Comment by rajatsrao** [comment]
Some background -
- My board is ZCU106 and I'm on Vivado 2020.2. I made some necessary modifications to the ZCU102 project (board/part number, version, constraints for ZCU106 pins). But no actual modifications to the design itself.
- I have the ARM Linux and devicetree compiled separately (not using petalinux) and I'm using the rootfs provided in this repo (initramfs.cpio.gz) from the zcu102 images directory.
- I have tried with the fesvr-zynq and libfesvr provided in the prebuilt images and with my own build - same result.

Regarding HTIF and the ARM devicetree, I asked that question because I see a UIO instance for it in system_user.dtsi. However, I extracted the devicetree from the prebuilt image.ub and disassembled it to look at the source (attached). It doesn't look like there is any HTIF entry here at all, or for that matter anything that has a memory map of 0xA0000000. Looking at the fesvr code, it uses /dev/mem directly, so is there any kernel module required for it? If yes, could you please point me to it?
[system.dts.txt](https://github.com/li3tuo4/rc-fpga-zcu/files/9491270/system.dts.txt)

**Comment by rajatsrao** [comment]
I did a little bit more probing with the ILA I have attached on the AXI bus. We can see that reading from address 0xa000000c is returning the value 0x10 -
![image](https://user-images.githubusercontent.com/57903194/188495693-e3207175-15cd-4841-9689-3bc7256f331e.png)

However, reading this value in the poll function of the program `read(TSI_IN_FIFO_COUNT);`  returns 0!
I even tried command line devmem to this address and that also returned 0, while clearly the data on the bus is nonzero.
```
# devmem 0xa000000c   
0x00000000
```

There's definitely a problem here, but I'm not sure why/what... In the poll function, `tsi->data_available()` returns true. So, if the count was read correctly, I think we would have made some progress.

**Comment by li3tuo4** [comment]
A few suggestions:

1. Check if pk binary is correctly loaded by frontend server (check elfloader function in fesvr); 

2. Then, you can check if pk is using the correct function (the function invoking htif not uart) to provide printf for application layer. 

We had an issue with cache coherency on ARM side, where sending reset signal via htif at the beginning must be protected by enforcing memory barrier `__sync_synchronize()`. This coherency issue can cause rocket core waiting for waking up forever. This is already patched, but may happen again due to the differences in the microarchitecture of PS side in zcu106.

**Comment by rajatsrao** [comment]
I'm definitely convinced that it's a memory coherency issue, but it doesn't work even with the `__sync_synchronize()`
I tried the same build steps on ZCU102 and everything works! I even removed the HTIF entry from the ARM device tree and as expected it continues to work. From the ARM side, it's just MMIO via /dev/mem and there's no HTIF device.

I'm closing this issue since it seems specific to non-ZCU102 setup and maybe I'm missing something.
