### ISSUE TITLE
Can it be used to generate BOOM on zcu102?

### ISSUE THREAD

**Issue by ProJeKTRED** [li3tuo4/rc-fpga-zcu#15]
like CONFIG=SmallBoomConfig
thank you

**Comment by li3tuo4** [comment]
No, this repo only supports rocket core. It might be achievable by heavily customizing this repo to integrate boom core (replacing rocket core in rocket chip).

**Comment by ProJeKTRED** [comment]
> No, this repo only supports rocket core. It might be achievable by heavily customizing this repo to integrate boom core (replacing rocket core in rocket chip).

ok，thanks
