### ISSUE TITLE
Building linux using config_freedom as .config does not boot on the zcu102

### ISSUE THREAD

**Issue by ncppd** [li3tuo4/rc-fpga-zcu#2]
Greetings Tuo,

I tried building the linux kernel using the configuration file `config_freedom` according to your [tutorial](https://github.com/li3tuo4/rc-zcu102-tutorial/blob/master/quickstart.pdf). I tested both the master branch (commit `513ce6d3080b43af80c4f0daaf7436c145c70a23`) & linux_u500vc707devkit_config branch (commit `db77bd7a8779d776d3f67b8a76ab5973e93604e6`), and linux won't boot. 

When I try to run `./fesvr-zynq bbl` on the zcu102 it hangs there and no output is provided. I tried running the bbl binary in spike and it boots fine, which excludes the possibility of a broken binary file.

On the contrary, the `bbl_linux` binary included in your [repo](https://github.com/li3tuo4/fpga-images-zcu/tree/893bac7d0a77d3e3cac72f26071daf49e87be61a) with the pre-built images boots fine on the FPGA board, so the problem may lie in the kernel configuration file? Did you use the same configuration file for the pre-built images?

Thanks and sorry for bothering you again!
Nick

**Comment by li3tuo4** [comment]
Hi Nick @ncppd ,

Thanks for letting me know this issue. The freedom-u-sdk has changed since my clone.
Did you see any error message during building bbl and riscv-linux? 
I am looking into this now. 

Thanks,
Tuo

**Comment by ncppd** [comment]
Hi Tuo,

No, there were no errors while building riscv-linux or bbl. I tried building the linux kernel using different configs found in [fpga-zynq](https://github.com/riscv-boom/fpga-zynq) repo (sw/ directory) and also in freedom-u-sdk and everything seem to work fine on spike but still fail to boot on the zcu102. After testing different configs I started suspecting that the problem might be caused by fesvr-zynq but to no avail, because bbl_linux and bbl_sel4test boot just fine. 

Thanks,
Nick

**Comment by li3tuo4** [comment]
Hi Nick,

Thanks for the feedback.
I tested again about petalinux build. The tutoiral is modfied for these changes as well as is refined for readability. In short, after you copy the config_freedom to freedom-u-sdk/conf and rename it to linux_defconfig, "make vmlinux" should do the work. The detail can be found in the new tutorial.

The fesvr-zynq, bbl, and bitstream in the prebuilt image is a bit different to the files created in the current Makefile, in terms of how the risc-v device tree is handled. The current Makefile is tested and should be fine. Using incorrect config in riscv-linux build can make executing bbl hang. 

Please let me know if this fix works for you.

Cheers,
Tuo

**Comment by ncppd** [comment]
Hi Tuo,

I spotted the mistake: I compiled the bbl using riscv-pk of the freedom-u-sdk's repo instead of using your modified version in rc-fpga-zcu. It now boots fine!

The new version of the tutorial indeed clarifies many dark corners in the whole process!

**Edit: Although the zcu102 has 4GB of DRAM I noticed through /proc/meminfo that ~260MB are allocated to riscv-linux. Do you know how can I increase the allocated memory? Should I modify the device-tree or riscv-fesvr?

Thanks again and sorry for the silly mistake,
Nick

**Comment by li3tuo4** [comment]
Hi Nick,

Glad to know this repo works for you now.

I kept the same memory size as the one used in ucb-bar's fpga-zynq repo, which is 256MB.
Yes, you can use more memory.  To do this, you probably need to modify (1) the address specification of ARM processing system, and, (2) RISC-V device tree.


Cheers,
Tuo

**Comment by ncppd** [comment]
Thank you for the info, I am looking into it.

Nick
