### ISSUE TITLE
machine `aarch64' not recognized

### ISSUE THREAD

**Issue by brlpush** [li3tuo4/rc-fpga-zcu#6]
I am getting the following error while executing make fesvr-zynq.

checking build system type... x86_64-unknown-linux-gnu
checking host system type... Invalid configuration `aarch64-linux-gnu': machine `aarch64' not recognized
configure: error: /bin/sh scripts/config.sub aarch64-linux-gnu failed

I saw the previous thread as well where they talk about the issue and later said they were able to resolve it but I couldn't figure out any definite solution. Please let me know if I am missing something here. 
I am using Vivado, SDK and Petalinxu 2018.3 and I have the Xilinx SDK added to my path as well.

https://github.com/li3tuo4/rc-fpga-zcu/issues/5#issuecomment-575149179 -- Here replacing config.sub and config.guess seems to solve the issue but replacing from where ?

**Comment by li3tuo4** [comment]
@brlpush A quick fix is to insert a newline  "| aarch64 \ " after [this line](https://github.com/riscv/riscv-fesvr/blob/68c12d06ebbdfe20856b886570822fe66804fd26/scripts/config.sub#L244) in [config.sub](https://github.com/riscv/riscv-fesvr/blob/68c12d06ebbdfe20856b886570822fe66804fd26/scripts/config.sub)

**Comment by brlpush** [comment]
Thanks for the reply. I am able to resolve it.
